# Generated by Django 5.2.3 on 2025-06-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='exact_location_text',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='drinking_habits',
        ),
        migrations.RemoveField(
            model_name='user',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='smoking_habits',
        ),
        migrations.AddField(
            model_name='user',
            name='drinks_alcohol',
            field=models.CharField(blank=True, choices=[('Often', 'Often'), ('Socially', 'Socially'), ('Rarely', 'Rarely'), ('Never', 'Never'), ('Prefer not to say', 'Prefer not to say')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='relationship_type',
            field=models.CharField(blank=True, choices=[('Monogamous', 'Monogamous'), ('Polyamorous', 'Polyamorous'), ('Open Relationship', 'Open Relationship'), ('Not Sure', 'Not Sure'), ('Prefer not to say', 'Prefer not to say')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='religion',
            field=models.CharField(blank=True, choices=[('Agnostic', 'Agnostic'), ('Atheist', 'Atheist'), ('Buddhist', 'Buddhist'), ('Christian', 'Christian'), ('Hindu', 'Hindu'), ('Jewish', 'Jewish'), ('Muslim', 'Muslim'), ('Spiritual', 'Spiritual'), ('Other', 'Other'), ('Prefer not to say', 'Prefer not to say')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='smokes',
            field=models.CharField(blank=True, choices=[('Often', 'Often'), ('Socially', 'Socially'), ('Rarely', 'Rarely'), ('Never', 'Never'), ('Prefer not to say', 'Prefer not to say')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='preferred_relationship_type_match',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='preferred_religion_match',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-binary', 'Non-binary'), ('Other', 'Other'), ('Prefer not to say', 'Prefer not to say')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='users', to='api.interest'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_completeness_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='relationship_intent',
            field=models.CharField(blank=True, choices=[('Long-term relationship', 'Long-term relationship'), ('Short-term relationship', 'Short-term relationship'), ('Friendship', 'Friendship'), ('Casual dating', 'Casual dating'), ('Still figuring it out', 'Still figuring it out')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='max_distance_km',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_age_max',
            field=models.IntegerField(default=99),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_age_min',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_relationship_intent',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_religion',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
