# Generated by Django 5.2.3 on 2025-06-17 11:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_exact_location_text_user_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepted_terms_and_conditions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
