# Generated by Django 5.2.3 on 2025-06-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_accepted_terms_and_conditions_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='preferred_max_age_gap',
            field=models.IntegerField(blank=True, help_text='How many years older they can be (e.g., 0 for same age or younger, 5 for up to 5 years older)', null=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='preferred_min_age_gap',
            field=models.IntegerField(blank=True, help_text='How many years younger they can be (e.g., 0 for same age or older, 2 for up to 2 years younger)', null=True),
        ),
    ]
