# Generated by Django 5.2.3 on 2025-06-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_user_location_user_city_user_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='relationship_intent',
            field=models.CharField(blank=True, choices=[('Long-term relationship', 'Long-term relationship'), ('Short-term relationship', 'Short-term relationship'), ('Casual dating', 'Casual dating'), ('Friendship', 'Friendship'), ("I'm not sure yet", "I'm not sure yet"), ('Prefer not to say', 'Prefer not to say')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='religion',
            field=models.CharField(blank=True, choices=[('Agnostic', 'Agnostic'), ('Atheist', 'Atheist'), ('Baháʼí', 'Baháʼí'), ('Buddhism', 'Buddhism'), ('Christianity', 'Christianity'), ('Hinduism', 'Hinduism'), ('Islam', 'Islam'), ('Jainism', 'Jainism'), ('Judaism', 'Judaism'), ('Shinto', 'Shinto'), ('Sikhism', 'Sikhism'), ('Spiritual but not religious', 'Spiritual but not religious'), ('Taoism', 'Taoism'), ('Other', 'Other'), ('Prefer not to say', 'Prefer not to say')], max_length=50, null=True),
        ),
    ]
