# Generated by Django 5.2.3 on 2025-06-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_relationship_intent_alter_user_religion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='drinks_alcohol',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Socially', 'Socially'), ('Occasionally', 'Occasionally'), ('Prefer not to say', 'Prefer not to say')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='relationship_type',
            field=models.CharField(blank=True, choices=[('Monogamous', 'Monogamous'), ('Polyamorous', 'Polyamorous'), ('Open to exploring', 'Open to exploring'), ('Prefer not to say', 'Prefer not to say')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='smokes',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Socially', 'Socially'), ('Occasionally', 'Occasionally'), ('Prefer not to say', 'Prefer not to say')], max_length=20, null=True),
        ),
    ]
