# Generated by Django 5.0.4 on 2024-05-20 12:00

from django.db import migrations

# List of interests to be added to the database
INTERESTS_LIST = [
    {"name": "Photography", "emoji": "📷"},
    {"name": "Traveling", "emoji": "✈️"},
    {"name": "Reading", "emoji": "📚"},
    {"name": "Writing", "emoji": "✍️"},
    {"name": "Cooking", "emoji": "🍳"},
    {"name": "Baking", "emoji": "🍰"},
    {"name": "Movies", "emoji": "🎬"},
    {"name": "TV Shows", "emoji": "📺"},
    {"name": "Music", "emoji": "🎵"},
    {"name": "Concerts", "emoji": "🎤"},
    {"name": "Dancing", "emoji": "💃"},
    {"name": "Singing", "emoji": "🎶"},
    {"name": "Gaming", "emoji": "🎮"},
    {"name": "Board Games", "emoji": "🎲"},
    {"name": "Sports", "emoji": "⚽"},
    {"name": "Fitness", "emoji": "💪"},
    {"name": "Yoga", "emoji": "🧘"},
    {"name": "Meditation", "emoji": "🧘‍♀️"},
    {"name": "Hiking", "emoji": "🥾"},
    {"name": "Camping", "emoji": "🏕️"},
    {"name": "Nature", "emoji": "🌳"},
    {"name": "Animals", "emoji": "🐾"},
    {"name": "Pets", "emoji": "🐶"},
    {"name": "Art", "emoji": "🎨"},
    {"name": "Painting", "emoji": "🖌️"},
    {"name": "Drawing", "emoji": "✏️"},
    {"name": "Crafting", "emoji": "✂️"},
    {"name": "DIY", "emoji": "🔨"},
    {"name": "Volunteering", "emoji": "❤️"},
    {"name": "Technology", "emoji": "💻"},
    {"name": "Science", "emoji": "🔬"},
    {"name": "History", "emoji": "📜"},
    {"name": "Politics", "emoji": "🏛️"},
    {"name": "Fashion", "emoji": "👗"},
    {"name": "Shopping", "emoji": "🛍️"},
    {"name": "Foodie", "emoji": "🍔"},
    {"name": "Coffee", "emoji": "☕"},
    {"name": "Tea", "emoji": "🍵"},
    {"name": "Wine", "emoji": "🍷"},
    {"name": "Beer", "emoji": "🍺"},
]

def seed_interests(apps, schema_editor):
    """Seeds the database with the interests from the list."""
    Interest = apps.get_model('api', 'Interest')
    for interest_data in INTERESTS_LIST:
        # get_or_create prevents creating duplicates if the interest already exists
        Interest.objects.get_or_create(name=interest_data['name'], defaults=interest_data)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_user_drinks_alcohol_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_interests),
    ]
