# Generated by Django 5.2.3 on 2025-07-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_seed_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphoto',
            name='photo_url',
            field=models.ImageField(max_length=512, upload_to='profile_pics/'),
        ),
    ]
