# Generated by Django 5.2.5 on 2025-08-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_user_is_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_gender',
            field=models.JSONField(blank=True, null=True, default=list),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_relationship_intent',
            field=models.JSONField(blank=True, null=True, default=list),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_relationship_type_match',
            field=models.JSONField(blank=True, null=True, default=list),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_religion',
            field=models.JSONField(blank=True, null=True, default=list),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_religion_match',
            field=models.JSONField(blank=True, null=True, default=list),
        ),
    ]
