# Generated by Django 5.2.5 on 2025-08-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_userpreference_preferred_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_gender',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name=models.CharField(max_length=50)),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_relationship_intent',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name=models.CharField(max_length=50)),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_relationship_type_match',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name=models.CharField(max_length=50)),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_religion',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name=models.CharField(max_length=50)),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_religion_match',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name=models.CharField(max_length=50)),
        ),
    ]
