# Generated by Django 5.2.5 on 2025-08-31 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_userpreference_preferred_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_payment_tx_ref',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
