# Generated by Django 5.0.6 on 2025-09-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_user_current_payment_tx_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ad_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='ad_free_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='boost_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='can_see_likes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_boost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='likes_reveal_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
