# Generated by Django 5.0.6 on 2025-10-05 08:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_user_ad_free_user_ad_free_expiry_user_boost_expiry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('liked', 'Liked'), ('removed', 'Removed'), ('matched', 'Matched')], default='liked', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('liked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_received', to=settings.AUTH_USER_MODEL)),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['liker', 'status'], name='api_like_liker_i_68abc6_idx'), models.Index(fields=['liked', 'status'], name='api_like_liked_i_fae111_idx'), models.Index(fields=['status', 'created_at'], name='api_like_status_926f78_idx')],
                'unique_together': {('liker', 'liked')},
            },
        ),
    ]
