# Generated by Django 5.0.6 on 2025-10-20 14:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('coins', models.IntegerField()),
                ('price_etb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus_coins', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['price_etb'],
            },
        ),
        migrations.CreateModel(
            name='GiftType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(max_length=10)),
                ('coin_cost', models.IntegerField()),
                ('etb_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['coin_cost'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_bank_code', models.CharField(default='', max_length=10)),
                ('owner_account_number', models.CharField(default='', max_length=50)),
                ('owner_account_name', models.CharField(default='', max_length=100)),
                ('owner_business_name', models.CharField(default='LunaLove Platform', max_length=100)),
                ('default_platform_cut', models.DecimalField(decimal_places=2, default=30.0, max_digits=5)),
                ('min_withdrawal_etb', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
        migrations.CreateModel(
            name='ChapaSubAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subaccount_id', models.CharField(max_length=100, unique=True)),
                ('bank_code', models.CharField(max_length=10)),
                ('account_number', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=100)),
                ('business_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chapa_subaccount', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoinPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_etb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coins_purchased', models.IntegerField()),
                ('chapa_tx_ref', models.CharField(max_length=100, unique=True)),
                ('chapa_checkout_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coinpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_purchases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GiftTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('total_coins', models.IntegerField()),
                ('total_etb_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_cut_percentage', models.DecimalField(decimal_places=2, default=30.0, max_digits=5)),
                ('platform_cut_etb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receiver_share_etb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('chapa_tx_ref', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('split_payment_processed', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts_sent', to=settings.AUTH_USER_MODEL)),
                ('gift_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gifttype')),
            ],
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.IntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_earned', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coin_wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
