# Generated by Django 5.2.4 on 2025-11-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_coinpackage_gifttype_platformsettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinpurchase',
            name='chapa_ref_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
