# Generated by Django 5.0.6 on 2025-12-12 19:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_subscriptionpurchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubaccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_code', models.CharField(max_length=10)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=200)),
                ('subaccount_id', models.CharField(max_length=100, unique=True)),
                ('split_type', models.CharField(default='percentage', max_length=20)),
                ('split_value', models.DecimalField(decimal_places=4, default=0.7, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('total_earnings_etb', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_withdrawn_etb', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subaccount', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
