# Generated by Cascade manual migration
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallet',
            name='balance_etb',
            field=models.DecimalField(max_digits=12, decimal_places=2, default=Decimal('0.00')),
        ),
        migrations.CreateModel(
            name='GiftTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coins_spent', models.PositiveIntegerField()),
                ('value_etb', models.DecimalField(max_digits=12, decimal_places=2)),
                ('commission_gross', models.DecimalField(max_digits=12, decimal_places=2, default=Decimal('0.00'))),
                ('vat_on_commission', models.DecimalField(max_digits=12, decimal_places=2, default=Decimal('0.00'))),
                ('commission_net', models.DecimalField(max_digits=12, decimal_places=2, default=Decimal('0.00'))),
                ('creator_payout', models.DecimalField(max_digits=12, decimal_places=2, default=Decimal('0.00'))),
                ('status', models.CharField(max_length=16, choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='SUCCESS')),
                ('failure_reason', models.CharField(max_length=255, blank=True, null=True)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payments.gift')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_gifts', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_gifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
