# Generated by Cascade for adding withdrawal support
from django.db import migrations, models
from django.conf import settings
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_wallet_gifttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='hold_etb',
            field=models.DecimalField(default=Decimal('0.00'), max_digits=12, decimal_places=2),
        ),
        migrations.AddField(
            model_name='wallet',
            name='kyc_level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(max_length=16)),
                ('destination', models.CharField(max_length=255)),
                ('amount_etb', models.DecimalField(max_digits=12, decimal_places=2)),
                ('status', models.CharField(max_length=16, default='PENDING', db_index=True)),
                ('provider_ref', models.CharField(max_length=128, null=True, blank=True)),
                ('failure_reason', models.CharField(max_length=255, null=True, blank=True)),
                ('approved_at', models.DateTimeField(null=True, blank=True)),
                ('paid_at', models.DateTimeField(null=True, blank=True)),
                ('user', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
