# Generated by Django 5.0.6 on 2025-09-02 14:48

import apps.payments.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_wallet_withdrawalrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='withdrawals_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='method',
            field=models.CharField(choices=[('CHAPA', 'Chapa'), ('TELEBIRR', 'Telebirr')], max_length=16),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], db_index=True, default='PENDING', max_length=16),
        ),
        migrations.CreateModel(
            name='KYCSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('NID', 'National ID'), ('PASSPORT', 'Passport')], max_length=16)),
                ('document', models.FileField(storage=apps.payments.storage.EncryptedFileSystemStorage(), upload_to='kyc/documents/')),
                ('selfie', models.FileField(storage=apps.payments.storage.EncryptedFileSystemStorage(), upload_to='kyc/selfies/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=16)),
                ('notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
