# Generated by Django 5.0.6 on 2025-09-05 08:55

import django.db.models.deletion
import django.utils.timezone
import payments.storage
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('target_net_etb', models.DecimalField(db_index=True, decimal_places=2, max_digits=12, unique=True)),
                ('coins', models.PositiveIntegerField(default=0)),
                ('base_etb', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vat_etb', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_total_etb', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('coins', models.PositiveIntegerField()),
                ('value_etb', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GiftTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coins_spent', models.PositiveIntegerField()),
                ('value_etb', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_gross', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('vat_on_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('commission_net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('creator_payout', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='SUCCESS', max_length=16)),
                ('failure_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payments.gift')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_gifts', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_gifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KYCSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('NID', 'National ID'), ('PASSPORT', 'Passport')], max_length=16)),
                ('document', models.FileField(storage=payments.storage.EncryptedFileSystemStorage(), upload_to='kyc/documents/')),
                ('selfie', models.FileField(storage=payments.storage.EncryptedFileSystemStorage(), upload_to='kyc/selfies/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=16)),
                ('notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], db_index=True, default='INITIATED', max_length=20)),
                ('provider', models.CharField(choices=[('CHAPA', 'Chapa'), ('TELEBIRR', 'Telebirr')], max_length=20)),
                ('provider_ref', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('checkout_url', models.URLField(blank=True, null=True)),
                ('price_total_etb', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('vat_etb', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('gw_fee_etb', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.coinpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_etb', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vat_etb', models.DecimalField(decimal_places=2, max_digits=12)),
                ('provider_ref', models.CharField(max_length=128)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='payments.payment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coin_balance', models.PositiveIntegerField(default=0)),
                ('is_banned', models.BooleanField(default=False)),
                ('balance_etb', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('hold_etb', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('kyc_level', models.PositiveSmallIntegerField(default=1)),
                ('withdrawals_blocked', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('CHAPA', 'Chapa'), ('TELEBIRR', 'Telebirr')], max_length=16)),
                ('destination', models.CharField(max_length=255)),
                ('amount_etb', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], db_index=True, default='PENDING', max_length=16)),
                ('provider_ref', models.CharField(blank=True, max_length=128, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
